# Copyright (c) 2026 Mechemsi. All rights reserved.
# Licensed under the MIT License. See LICENSE file in the project root.
#
# One entrypoint for setup, lifecycle and updates. No new dependencies —
# everything here shells out to docker, docker compose and the repo's scripts.

SHELL := /usr/bin/env bash
.DEFAULT_GOAL := help

COMPOSE      := docker compose
PY_IMAGE     := python:3.12
ORCHESTRATOR := $(CURDIR)/orchestrator
RUNNER_VERSION ?= 2.335.1
API_PORT     ?= 8080

.PHONY: help setup up down restart logs ps rebuild update runner-image \
        dashboard token test lint fmt check build-images clean

help: ## Show this help
	@grep -hE '^[a-z-]+:.*?## ' $(MAKEFILE_LIST) \
	  | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'

# ── setup ──────────────────────────────────────────────────────────────────

setup: .env config.yml runner-image ## First-time setup: scaffold .env + config.yml, build runner image
	@echo
	@echo "Setup complete. Edit .env (GITHUB_PAT) and config.yml (pools), then: make up"

.env: ## Scaffold .env from the example, with a generated dashboard token
	@if [ ! -f .env ]; then \
	  cp .env.example .env; \
	  token=$$(head -c 18 /dev/urandom | base64 | tr -d '/+='); \
	  printf '\n# Generated by `make setup` — dashboard auth token.\nRORCH_API_TOKEN=%s\n' "$$token" >> .env; \
	  echo "==> Created .env (set GITHUB_PAT before starting)"; \
	else echo "==> .env already exists, leaving it alone"; fi

config.yml: ## Scaffold config.yml from example.config.yml
	@if [ ! -f config.yml ]; then \
	  cp example.config.yml config.yml; \
	  echo "==> Created config.yml (edit your pools)"; \
	else echo "==> config.yml already exists, leaving it alone"; fi

runner-image: ## Build the runner image for this host's docker GID
	@RUNNER_VERSION=$(RUNNER_VERSION) ./scripts/build-runner.sh

# ── lifecycle ──────────────────────────────────────────────────────────────

up: ## Start the orchestrator
	$(COMPOSE) up -d
	@echo "==> Dashboard: http://127.0.0.1:$(API_PORT)/?token=$$(grep -s '^RORCH_API_TOKEN=' .env | cut -d= -f2-)"

down: ## Stop the orchestrator (runner containers are left alone)
	$(COMPOSE) down

restart: down up ## Recreate the orchestrator container

logs: ## Follow orchestrator logs
	$(COMPOSE) logs -f orchestrator

ps: ## Show orchestrator and runner containers
	@docker ps --filter name=gh-runner --format 'table {{.Names}}\t{{.Image}}\t{{.Status}}'

dashboard: ## Print the dashboard URL including the auth token
	@echo "http://127.0.0.1:$(API_PORT)/?token=$$(grep -s '^RORCH_API_TOKEN=' .env | cut -d= -f2-)"

token: ## Print just the dashboard auth token
	@grep -s '^RORCH_API_TOKEN=' .env | cut -d= -f2-

# ── updates ────────────────────────────────────────────────────────────────

rebuild: runner-image ## Rebuild the runner image and recreate the orchestrator
	$(COMPOSE) up -d --build --force-recreate

update: ## Rebuild at RUNNER_VERSION (default: newest) and recreate
	@echo "==> Updating runner agent to $(RUNNER_VERSION)"
	@RUNNER_VERSION=$(RUNNER_VERSION) ./scripts/build-runner.sh
	$(COMPOSE) up -d --build --force-recreate

# ── development (all inside docker, per CLAUDE.md) ─────────────────────────

test: ## Run the test suite
	@docker run --rm -v "$(CURDIR):/repo" -w /repo/orchestrator $(PY_IMAGE) \
	  bash -c "pip install -q -e '.[dev]' && pytest -q --cov=rorch --cov-report=term-missing"

lint: ## Ruff + pyright
	@docker run --rm -v "$(CURDIR):/repo" -w /repo/orchestrator $(PY_IMAGE) \
	  bash -c "pip install -q -e '.[dev]' && ruff check rorch/ tests/ && ruff format --check rorch/ tests/ && pyright rorch/"

fmt: ## Apply ruff formatting and autofixes
	@docker run --rm -v "$(CURDIR):/repo" -w /repo/orchestrator $(PY_IMAGE) \
	  bash -c "pip install -q ruff && ruff check rorch/ tests/ --fix && ruff format rorch/ tests/"

check: lint test ## Everything CI runs for the Python package

build-images: ## Validate both Dockerfiles build (what CI's build job does)
	docker build -t gh-runner-orchestrator:check ./orchestrator
	docker build --build-arg RUNNER_VERSION=$(RUNNER_VERSION) -t gh-runner:check ./runner-image

clean: ## Remove check images built by build-images
	-docker rmi gh-runner-orchestrator:check gh-runner:check
