#!/usr/bin/env bash
set -euo pipefail

# Copyright (c) 2026 Mechemsi. All rights reserved.
# Licensed under the MIT License. See LICENSE file in the project root.

# check-deps.sh — Check for outdated and vulnerable Python dependencies.
# Creates GitHub issues via `gh` CLI when problems are found.
#
# Usage: ./scripts/check-deps.sh
#
# Requires: pip, pip-audit, gh (GitHub CLI, authenticated)

REPO_ROOT="$(git -C "$(dirname "$0")/.." rev-parse --show-toplevel)"
REQ_FILE="$REPO_ROOT/orchestrator/requirements.txt"

OUTDATED_ISSUE_TITLE="deps: outdated Python packages found"
VULN_ISSUE_TITLE="security: vulnerable Python packages found"

# ── Helpers ──────────────────────────────────────────────────────────────────

issue_exists() {
    local title="$1"
    local count
    count="$(gh issue list --repo "$GITHUB_REPOSITORY" --state open --search "$title" --json title --jq "[.[] | select(.title == \"$title\")] | length")"
    [[ "$count" -gt 0 ]]
}

# ── Install tools ────────────────────────────────────────────────────────────

pip install --quiet --disable-pip-version-check -r "$REQ_FILE"
pip install --quiet --disable-pip-version-check pip-audit

# ── Check outdated packages ──────────────────────────────────────────────────

echo "=== Checking for outdated packages ==="
outdated_output=""
outdated_output="$(pip list --outdated --format=json -r "$REQ_FILE" 2>/dev/null)" || true

outdated_count=0
outdated_body=""
if [[ -n "$outdated_output" && "$outdated_output" != "[]" ]]; then
    outdated_count="$(echo "$outdated_output" | python3 -c "import sys,json; print(len(json.load(sys.stdin)))")"

    outdated_body="## Outdated Python Packages

The following packages in \`orchestrator/requirements.txt\` have newer versions available.

| Package | Current | Latest | Type |
|---------|---------|--------|------|
"
    outdated_body+="$(echo "$outdated_output" | python3 -c "
import sys, json
for p in json.load(sys.stdin):
    print(f\"| {p['name']} | {p['version']} | {p['latest_version']} | {p['latest_filetype']} |\")")
"

    outdated_body+="
### Recommended Action
Update \`orchestrator/requirements.txt\` with the latest compatible versions and run tests.

---
*Auto-generated by CI dependency check.*"
fi

# ── Check vulnerabilities ────────────────────────────────────────────────────

echo "=== Checking for vulnerabilities ==="
vuln_output=""
vuln_exit=0
vuln_output="$(pip-audit -r "$REQ_FILE" --format=json 2>/dev/null)" || vuln_exit=$?

vuln_count=0
vuln_body=""
if [[ $vuln_exit -ne 0 && -n "$vuln_output" ]]; then
    vuln_count="$(echo "$vuln_output" | python3 -c "
import sys, json
data = json.load(sys.stdin)
deps = data.get('dependencies', [])
total = sum(len(d.get('vulns', [])) for d in deps)
print(total)")"

    if [[ "$vuln_count" -gt 0 ]]; then
        vuln_body="## Vulnerable Python Packages

The following packages in \`orchestrator/requirements.txt\` have known security vulnerabilities.

| Package | Version | Vulnerability | Fix Versions | Description |
|---------|---------|---------------|--------------|-------------|
"
        vuln_body+="$(echo "$vuln_output" | python3 -c "
import sys, json
data = json.load(sys.stdin)
for dep in data.get('dependencies', []):
    for v in dep.get('vulns', []):
        fix = v.get('fix_versions', [])
        fix_str = ', '.join(fix) if fix else 'N/A'
        desc = v.get('description', 'N/A')[:80].replace('|', '-')
        vuln_id = v.get('id', 'N/A')
        print(f\"| {dep['name']} | {dep['version']} | {vuln_id} | {fix_str} | {desc} |\")")
"

        vuln_body+="
### Recommended Action
Upgrade affected packages to the fix versions listed above. Prioritize by severity.

---
*Auto-generated by CI dependency check.*"
    fi
fi

# ── Report ───────────────────────────────────────────────────────────────────

echo ""
echo "=== Results ==="
echo "Outdated packages: $outdated_count"
echo "Vulnerabilities:   $vuln_count"

exit_code=0

# ── Create issues ────────────────────────────────────────────────────────────

if [[ "$outdated_count" -gt 0 ]]; then
    echo ""
    echo "--- Outdated packages report ---"
    echo "$outdated_body"
    if [[ -n "${GITHUB_REPOSITORY:-}" ]]; then
        if issue_exists "$OUTDATED_ISSUE_TITLE"; then
            echo "Issue already open, skipping."
        else
            gh issue create \
                --repo "$GITHUB_REPOSITORY" \
                --title "$OUTDATED_ISSUE_TITLE" \
                --body "$outdated_body" \
                --label "dependencies"
            echo "Created outdated packages issue."
        fi
    fi
    exit_code=1
fi

if [[ "$vuln_count" -gt 0 ]]; then
    echo ""
    echo "--- Vulnerability report ---"
    echo "$vuln_body"
    if [[ -n "${GITHUB_REPOSITORY:-}" ]]; then
        if issue_exists "$VULN_ISSUE_TITLE"; then
            echo "Issue already open, skipping."
        else
            gh issue create \
                --repo "$GITHUB_REPOSITORY" \
                --title "$VULN_ISSUE_TITLE" \
                --body "$vuln_body" \
                --label "security"
            echo "Created vulnerability issue."
        fi
    fi
    exit_code=1
fi

exit $exit_code
